const assert = require('node:assert/strict');
require('../app/timer-state.js');
const T = globalThis.TimerState;
const day = { phases: [{ label: 'A', minutes: 1 }, { label: 'B', minutes: 2 }] };
const reload = s => JSON.parse(JSON.stringify(s));
let s = T.action(null, day, 1000, 'toggle');
assert.equal(T.advance(reload(s), day, 31000).remainingMs, 30000);
s = T.action(s, day, 31000, 'toggle');
assert.equal(T.advance(reload(s), day, 999000).remainingMs, 30000);
s = T.action(s, day, 1000000, 'toggle');
s = T.advance(reload(s), day, 1045000);
assert.equal(s.phaseIdx, 1);
assert.equal(s.remainingMs, 105000);
assert.equal(s.history.length, 1);
s = T.advance(reload(s), day, 9999999);
assert.equal(s.completed, true);
assert.equal(s.running, false);
assert.equal(s.history.length, 2);
assert.equal(s.history.reduce((a, h) => a + h.actualSec, 0), 180);
assert.deepEqual(T.advance(reload(s), day, 99999999), s);
assert.deepEqual(T.action(s, day, 99999999, 'skip'), s);
assert.deepEqual(T.action(s, day, 99999999, 'toggle'), s);
s = T.action(null, day, 1000, 'toggle');
s = T.action(s, day, 11500, 'skip');
assert.equal(s.history[0].actualSec, 10.5);
assert.equal(s.remainingMs, 120000);
assert.equal(s.running, true);
assert.deepEqual(T.action(s, day, 12000, 'reset'), T.fresh(day));
assert.equal(T.advance(T.action(null, day, 1000, 'toggle'), day, 0).remainingMs, 60000);
assert.equal(T.action(null, { phases: [] }, 0, 'toggle').running, false);
console.log('PASS: restart, pause, resume, phase catch-up, completion, replay, skip, reset, clock rollback, empty day');
